[package]
name = "rust_c_compiler"
version = "0.1.0"
authors = ["Mitchell Hynes <mshynes@mun.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9"
